//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Kaynak {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Kaynak() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebProje.Resources.Kaynak", typeof(Kaynak).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Girişi.
        /// </summary>
        public static string AdminGirisi {
            get {
                return ResourceManager.GetString("AdminGirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Giriş Sayfası.
        /// </summary>
        public static string AdminGirisSayfasi {
            get {
                return ResourceManager.GetString("AdminGirisSayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketbol.
        /// </summary>
        public static string Basketbol {
            get {
                return ResourceManager.GetString("Basketbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlığa Göre Bul:.
        /// </summary>
        public static string BasligaGoreBul {
            get {
                return ResourceManager.GetString("BasligaGoreBul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtilmemiş.
        /// </summary>
        public static string Belirtilmemis {
            get {
                return ResourceManager.GetString("Belirtilmemis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string CikisYap {
            get {
                return ResourceManager.GetString("CikisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Takımlar.
        /// </summary>
        public static string DigerTakimlar {
            get {
                return ResourceManager.GetString("DigerTakimlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Duzenle {
            get {
                return ResourceManager.GetString("Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleyen Kişi.
        /// </summary>
        public static string EkleyenKisi {
            get {
                return ResourceManager.GetString("EkleyenKisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adresi.
        /// </summary>
        public static string EmailAdresi {
            get {
                return ResourceManager.GetString("EmailAdresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Çok Tıklanılanlar.
        /// </summary>
        public static string EnCokTiklanilanlar {
            get {
                return ResourceManager.GetString("EnCokTiklanilanlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string EPosta {
            get {
                return ResourceManager.GetString("EPosta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futbol.
        /// </summary>
        public static string Futbol {
            get {
                return ResourceManager.GetString("Futbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string GeriDon {
            get {
                return ResourceManager.GetString("GeriDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz E-Posta veya Kullanıcı Adı Sistemde Kayıtlı..
        /// </summary>
        public static string Girdiginiz {
            get {
                return ResourceManager.GetString("Girdiginiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string GirisYap {
            get {
                return ResourceManager.GetString("GirisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapılan Kullanıcı.
        /// </summary>
        public static string GirisYapilanKullanici {
            get {
                return ResourceManager.GetString("GirisYapilanKullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapıldı Mı.
        /// </summary>
        public static string GirisYapildiMi {
            get {
                return ResourceManager.GetString("GirisYapildiMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber.
        /// </summary>
        public static string Haber {
            get {
                return ResourceManager.GetString("Haber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Başlığı.
        /// </summary>
        public static string HaberBasligi {
            get {
                return ResourceManager.GetString("HaberBasligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberi Gör.
        /// </summary>
        public static string HaberiGor {
            get {
                return ResourceManager.GetString("HaberiGor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string Haberler {
            get {
                return ResourceManager.GetString("Haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Tarihi.
        /// </summary>
        public static string HaberTarihi {
            get {
                return ResourceManager.GetString("HaberTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HATA!.
        /// </summary>
        public static string Hata {
            get {
                return ResourceManager.GetString("Hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        public static string Hosgeldiniz {
            get {
                return ResourceManager.GetString("Hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemler.
        /// </summary>
        public static string Islemler {
            get {
                return ResourceManager.GetString("Islemler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Kategori {
            get {
                return ResourceManager.GetString("Kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Formu.
        /// </summary>
        public static string KayitFormu {
            get {
                return ResourceManager.GetString("KayitFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string KayitOl {
            get {
                return ResourceManager.GetString("KayitOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string KullaniciAdi {
            get {
                return ResourceManager.GetString("KullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adınız.
        /// </summary>
        public static string KullaniciAdiniz {
            get {
                return ResourceManager.GetString("KullaniciAdiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeye Dön.
        /// </summary>
        public static string ListeyeDon {
            get {
                return ResourceManager.GetString("ListeyeDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milli Takım.
        /// </summary>
        public static string MilliTakim {
            get {
                return ResourceManager.GetString("MilliTakim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKU.
        /// </summary>
        public static string Oku {
            get {
                return ResourceManager.GetString("Oku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okunma Sayısı.
        /// </summary>
        public static string OkunmaSayisi {
            get {
                return ResourceManager.GetString("OkunmaSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string Onay {
            get {
                return ResourceManager.GetString("Onay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanmamış.
        /// </summary>
        public static string Onaylanmamış {
            get {
                return ResourceManager.GetString("Onaylanmamış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanmış.
        /// </summary>
        public static string Onaylanmis {
            get {
                return ResourceManager.GetString("Onaylanmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki.
        /// </summary>
        public static string Onceki {
            get {
                return ResourceManager.GetString("Onceki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfası.
        /// </summary>
        public static string Sayfasi {
            get {
                return ResourceManager.GetString("Sayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Hatırla.
        /// </summary>
        public static string SifremiHatirla {
            get {
                return ResourceManager.GetString("SifremiHatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Haberler.
        /// </summary>
        public static string SonHaberler {
            get {
                return ResourceManager.GetString("SonHaberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki.
        /// </summary>
        public static string Sonraki {
            get {
                return ResourceManager.GetString("Sonraki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string Soyad {
            get {
                return ResourceManager.GetString("Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        public static string Soyadi {
            get {
                return ResourceManager.GetString("Soyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye.
        /// </summary>
        public static string Uye {
            get {
                return ResourceManager.GetString("Uye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Adı.
        /// </summary>
        public static string UyeAdi {
            get {
                return ResourceManager.GetString("UyeAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Girişi.
        /// </summary>
        public static string UyeGirisi {
            get {
                return ResourceManager.GetString("UyeGirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeler.
        /// </summary>
        public static string Uyeler {
            get {
                return ResourceManager.GetString("Uyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeler Listesi.
        /// </summary>
        public static string UyelerListesi {
            get {
                return ResourceManager.GetString("UyelerListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik Tarihi.
        /// </summary>
        public static string UyelikTarihi {
            get {
                return ResourceManager.GetString("UyelikTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Yorumları.
        /// </summary>
        public static string UyeYorumlari {
            get {
                return ResourceManager.GetString("UyeYorumlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Haber Ekle.
        /// </summary>
        public static string YeniHaberEkle {
            get {
                return ResourceManager.GetString("YeniHaberEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Üye.
        /// </summary>
        public static string YeniUye {
            get {
                return ResourceManager.GetString("YeniUye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum.
        /// </summary>
        public static string Yorum {
            get {
                return ResourceManager.GetString("Yorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumla.
        /// </summary>
        public static string Yorumla {
            get {
                return ResourceManager.GetString("Yorumla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumunuzu Yazabilirsiniz.
        /// </summary>
        public static string YorumunuzuYazabilirsiniz {
            get {
                return ResourceManager.GetString("YorumunuzuYazabilirsiniz", resourceCulture);
            }
        }
    }
}
